# Site settings
name: Mathias Lindholm
description: Mathias Lindholm. I’m a designer working with digital products and services. I enjoy designing user interfaces, developing brand identities and designing type.
avatar: /img/avatar_2x.jpg
url: http://mlindholm.com
baseurl: ""

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: /:title/

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :compressed # You might prefer to minify using :compressed

# Gems to use
gems:
  - octopress-autoprefixer

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
