# Site settings
name: Mathias Lindholm
description: I’m a designer from Helsinki working with digital products and services.
url: http://mathiaslindholm.com
google_analytics: UA-35949347-3
baseurl: ""

# Work settings
# defaults:
#   - scope:
#       path: ""
#       type: posts
#     values:
#       permalink: /work/:title/

# Build settings
markdown: kramdown
permalink: /:title/

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :compressed # You might prefer to minify using :compressed

# Gems to use
gems:
  - octopress-autoprefixer

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
