# Site settings
name: Mathias Lindholm
description: "Mathias Lindholm is a product designer from Helsinki. I spend most of my time designing user interfaces, developing brand identities and occasionally I design type."
url: http://mathiaslindholm.com
google_analytics: UA-35949347-3
baseurl: ""

# Build settings
markdown: kramdown
permalink: /:title/

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :compressed # You might prefer to minify using :compressed

# Gems to use
gems:
  - octopress-autoprefixer

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - vendor
